// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Index from "./index";

import '../styles/globals.css'
;

var make = Index;

var MyApp = {
  make: make
};

function _appss$default(Props) {
  return React.createElement("div", {
              style: {
                backgroundColor: "#000",
                height: "100vh",
                width: "100%"
              }
            }, React.createElement(make, {}));
}

var $$default = _appss$default;

export {
  MyApp ,
  $$default ,
  $$default as default,
  
}
/*  Not a pure module */
