// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Index from "./index";

import '../styles/globals.css'
;

var make = Index;

var MyApp = {
  make: make
};

function _app$default(Props) {
  return React.createElement("div", undefined, React.createElement(make, {}));
}

var $$default = _app$default;

export {
  MyApp ,
  $$default ,
  $$default as default,
  
}
/*  Not a pure module */
