// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Container from "./Container";

import '../styles/globals.css'
;

var PageComponent = {};

var make = Container;

var Container$1 = {
  make: make
};

function $$default(props) {
  var content = React.createElement(props.Component, props.pageProps);
  return React.createElement(make, {
              children: content
            });
}

export {
  PageComponent ,
  Container$1 as Container,
  $$default ,
  $$default as default,
  
}
/*  Not a pure module */
