// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function About$default(Props) {
  return React.createElement("div", {
              style: {
                color: "#FFF"
              }
            }, "about");
}

var $$default = About$default;

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
