// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var name = "Hello world";

var element = name !== undefined ? React.createElement("div", undefined, "Hello " + name) : null;

function Index$default(Props) {
  return React.createElement("div", {
              style: {
                backgroundColor: "#000",
                height: "100vh",
                width: "100%"
              }
            }, element);
}

var $$default = Index$default;

export {
  name ,
  element ,
  $$default ,
  $$default as default,
  
}
/* element Not a pure module */
