// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Index$default(Props) {
  return React.createElement("div", undefined, React.createElement("p", {
                  style: {
                    color: "#FFF",
                    fontSize: "2.1rem",
                    textAlign: "justify",
                    textDecoration: "underline",
                    textDecorationColor: "#ad2f40"
                  }
                }, "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \r\n                Lorem Ipsum has been the industry's standard dummy text"));
}

var $$default = Index$default;

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
